backend/src/abi/EtherspotChainlinkOracleAbi.ts, backend/src/routes/index.ts
- Added custom chainlink oracle price update from coingecko and setting it to the paymaster
- Added a few more env for coingecko url and its ids for each custom chainlink erc20 paymaster 
-
=> Custom Chainlink Oracle CronJob

.github/workflows/check-package-version.yml, .github/workflows/release.yml
- Add CI config to publish docker image of `backend`
- Add CI config to check if package version is bumped
-
=> Implement Docker publish pipeline

.github/workflows/release.yml
- Fixed build pipeline and upgraded actions to new versions 
-
=> fix: pipeline config and upgrade actions

backend/package.json, backend/src/paymaster/index.ts, backend/src/routes/index.ts
- removed forced signature overwrite of '0x' value before estimating
-
=> Removed UserOp Signature Overwrite

admin_frontend/package-lock.json, admin_frontend/package.json, backend/config.json.default, backend/package.json, backend/src/abi/ChainlinkOracleAbi.ts, backend/src/paymaster/index.ts, backend/src/routes/index.ts, frontend/package-lock.json, frontend/package.json
- Added config to use multitoken to all chains
- Tested on Linea Mainnet https://lineascan.build/tx/0xa68f16237c09b895387f136ad69e14c98f9815f964071f6ace86e0263d7564b2
=> PRO-2396-MultiTokenPaymaster Linea Deployment

admin_frontend/package.json, backend/package.json, backend/src/constants/ErrorMessage.ts, backend/src/routes/paymaster-routes.ts, backend/src/routes/sponsorship-policy-routes.ts, backend/src/utils/common.ts, frontend/package.json
https://linear.app/pillarproject/issue/PRO-2544/arka-paymaster-sponsorship-policy-and-paymasterdata-generation-bug
- [ X] Bugfix (non-breaking change which fixes an issue)
- [X ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> fix: PRO-2522 SponsorshipPolicy Creation and PaymasterData Generation

admin_frontend/package-lock.json, admin_frontend/package.json, backend/migrations/20240725000001-update-apiKey-table.cjs, backend/package.json, backend/src/abi/ERC20PaymasterV07Abi.ts, backend/src/models/api-key.ts, backend/src/paymaster/index.ts, backend/src/routes/paymaster-routes.ts, frontend/package-lock.json, frontend/package.json
- Added support for erc20 paymaster on epV07
- Added new column on apiKeys table for the deployments on erc20 paymaster v07
-
=> PRO-2509-ERC20PaymasterV07

backend/migrations/20240725000001-update-apiKey-table.cjs
- changed db name to the same as env db name
-
=> Migration Bug Fix

backend/config.json.default, backend/src/routes/paymaster-routes.ts
- Added new networks to default network config
- Fixed a bug where error to be thrown if the token isnt found
-
=> Added default config networks

admin_frontend/package-lock.json, admin_frontend/package.json, backend/migrations/2024080800001-create-contract-whitelist.cjs, backend/migrations/2024080800002-update-apiKey.cjs, backend/package.json, backend/src/constants/ErrorMessage.ts, backend/src/models/api-key.ts, backend/src/models/contract-whitelist.ts, backend/src/paymaster/index.ts, backend/src/plugins/config.ts, backend/src/plugins/sequelizePlugin.ts, backend/src/repository/contract-whitelist-repository.ts, backend/src/routes/paymaster-routes.ts, backend/src/routes/whitelist-routes.ts, backend/src/types/contractWhitelist-dto.ts, frontend/package-lock.json, frontend/package.json
- Added a new table for Contract whitelisting based on the sponsor wallet address
- Added new env var for EPv07 token paymasters VGL and PGL
- Added migrations as modicifactions are done on apiKeys to include another column for enabling contract whitelisting
-
=> PRO-2501-Arka_Contract_Events_Whitelist

backend/src/routes/paymaster-routes.ts
- Dumped networkConfig fetched on logs
-
=> Added essential log

backend/package.json, backend/src/routes/deposit-route.ts, backend/src/routes/metadata-routes.ts, backend/src/routes/paymaster-routes.ts, backend/src/routes/pimlico-routes.ts, backend/src/routes/whitelist-routes.ts
- Added type checks for apiKey as string
-
=> added type check for apiKey as string

backend/package.json, backend/src/server.ts
=> update: adding bundler api-key to url in cron: checkPaymasterDeposit

backend/package.json, backend/src/paymaster/index.ts
- Exchange rate fix for tokens other than 6 decimals fix for multitoken paymasters
- have tested locally https://scan.ancient8.gg/tx/0xa0f2abfb7b42d4743952f468310120516deda941d978e040ae44259c514b7ec6
=> Exchange_Rate_Bug_Fix

backend/package.json, backend/src/paymaster/index.ts
- Changed Return type of ethUSDPrice on pm_getTokenQuotes as per standard
-
=> PmgetTokenQuotes_Return_Type_Fix

backend/package.json, backend/src/plugins/config.ts, backend/src/routes/admin-routes.ts
- Added default bundler api key.
- including bundler key on /saveKey endpoint.
=> ft: adding default bundler key for /saveKey endpoint

backend/config.json.default, backend/package.json
- Add support for opBNB 
- Change links to chainIds
-
=> feat: Add opBNB support

backend/src/utils/crypto.ts
=> fix: minor import fix

backend/src/routes/metadata-routes.ts
- private key init fix for metadata v2 route
-
=> fix metadata v2 route for private key init

backend/CHANGELOG.md, backend/package.json, backend/src/paymaster/index.ts, backend/src/routes/metadata-routes.ts, backend/src/server.ts, backend/src/services/coingecko.ts, backend/src/utils/common.ts
- Updated code from master branch which includes emergency fix commit 
- Updated Error Handling for coingecko tokens
-
=> PRO-2751-Updated_From_Master_Branch

backend/src/paymaster/index.ts, backend/src/server.ts, backend/src/services/coingecko.ts
- checking for coingecko price logs
-
=> Logs on QA

backend/src/paymaster/index.ts, backend/src/routes/paymaster-routes.ts
- Check if the address is present or not in the object rather than error out on undefined object
-
=> MTP Error Handling

backend/CHANGELOG.md, backend/package.json, backend/src/routes/pimlico-routes.ts, backend/src/routes/sponsorship-policy-routes.ts
- changed `pimlicoAddress` endpoint name to `tokenPaymasterAddress` the functionality remains the same
- Changed the following endpoint names to be camelCases:-
- `/policy/wallet-address/:walletAddress` to `/policy/walletAddress/:walletAddress`
- `/policy/wallet-address/:walletAddress/ep-version/:epVersion` to `/policy/walletAddress/:walletAddress/epVersion/:epVersion`
- `/policy/wallet-address/:walletAddress/ep-version/:epVersion/chain-id/:chainId` to `/policy/walletAddress/:walletAddress/epVersion/:epVersion/chainId/:chainId`
- `/policy/wallet-address/:walletAddress/latest` to `/policy/walletAddress/:walletAddress/latest`
- `/policy/wallet-address/:walletAddress/chain-id/:chainId/latest` to `/policy/walletAddress/:walletAddress/chainId/:chainId/latest`
- …
=> api endpoint changes for policy related apis

backend/CHANGELOG.md, backend/package.json, backend/src/constants/ErrorMessage.ts, backend/src/constants/MultitokenPaymaster.ts, backend/src/paymaster/index.ts, backend/src/routes/paymaster-routes.ts
- Changed error message to more meaningful reply
- Added API to reflect whats been cached on runtime
-
=> Error_Handling

backend/migrations/20250106065640-add-vp7-contracts-to-default-key.cjs, backend/migrations/20250203163722-update-public-key.cjs
- creating migration script to change public key
-
=> ft: adding migration scripts for public key migration

backend/CHANGELOG.md, backend/src/paymaster/index.ts, backend/src/plugins/config.ts, backend/src/utils/common.ts
- using skandha for better gas estimations
=> ft: using skandha for gas data

backend/CHANGELOG.md, backend/package.json, backend/src/constants/ErrorMessage.ts, backend/src/routes/admin-routes.ts, backend/src/routes/deposit-route.ts, backend/src/routes/paymaster-routes.ts, backend/src/routes/pimlico-routes.ts, backend/src/routes/sponsorship-policy-routes.ts, backend/src/routes/whitelist-routes.ts
- Checked for undefined values on body params
-
=> Empty Body Fix

backend/CHANGELOG.md, backend/migrations/20250106065640-add-vp7-contracts-to-default-key.cjs, backend/migrations/20250203163722-update-public-key.cjs, backend/package.json, backend/src/constants/ErrorMessage.ts, backend/src/constants/MultitokenPaymaster.ts, backend/src/paymaster/index.ts, backend/src/plugins/config.ts, backend/src/routes/admin-routes.ts, backend/src/routes/deposit-route.ts, backend/src/routes/paymaster-routes.ts, backend/src/routes/pimlico-routes.ts, backend/src/routes/sponsorship-policy-routes.ts, backend/src/routes/whitelist-routes.ts, backend/src/utils/common.ts
- Rebased to master from develop in order to push Release PR
-
=> Rebased To Master Branch

backend/CHANGELOG.md, backend/package.json
* added checks for empty body
- Merged To Master from develop
-
=> MergedToMaster_120225

backend/CHANGELOG.md, backend/migrations/20250106065640-add-vp7-contracts-to-default-key.cjs, backend/migrations/20250203163722-update-public-key.cjs, backend/package.json, backend/src/constants/ErrorMessage.ts, backend/src/constants/MultitokenPaymaster.ts, backend/src/paymaster/index.ts, backend/src/plugins/config.ts, backend/src/routes/admin-routes.ts, backend/src/routes/deposit-route.ts, backend/src/routes/paymaster-routes.ts, backend/src/routes/pimlico-routes.ts, backend/src/routes/sponsorship-policy-routes.ts, backend/src/routes/whitelist-routes.ts, backend/src/utils/common.ts
- Empty Body Fix
- Adding migration scripts for public key migration
- Using skandha for gas data
-
=> Release 11-02-2025

backend/CHANGELOG.md, backend/package.json, backend/src/paymaster/index.ts, backend/src/plugins/config.ts, backend/src/routes/admin-routes.ts, backend/src/routes/deposit-route.ts, backend/src/routes/whitelist-routes.ts, backend/src/server.ts
- On signing EP7 paymaster the resultant paymasterVerificationGasLimit came out as string rather than HexString, fixed that for standardization 
- On coingecko prices for testing purpose included to not get one token fixed that too
- I don't think a new version is required for this fix
=> Fixed Standardization

backend/CHANGELOG.md, backend/package.json, backend/src/repository/multi-token-paymaster.ts
- Fixed cronJob invalid address error 
-
=> fixed cronJob error

backend/CHANGELOG.md, backend/package.json, backend/src/paymaster/index.ts
- Fixed Verifying Paymaster execution for undeployed wallets
-
=> VerifyingPaymaster Bug Fix

backend/CHANGELOG.md, backend/package.json, backend/src/constants/ErrorMessage.ts, backend/src/models/sponsorship-policy.ts, backend/src/routes/deposit-route.ts, backend/src/server.ts
- Changed all endpoints to be case-insensitive
- Fetch `globalMaximumUsd` value to convert into Number for absolute value
- Improve error handling in deposit apis
-
=> PRO-3083 - Arka Improvements

backend/CHANGELOG.md, backend/config.json.default, backend/package.json, backend/src/constants/MultitokenPaymaster.ts
- Added all token decimals in constants rather than fetching from rpc
-
=> Cron_Job_Fix

backend/src/routes/whitelist-routes.ts
=> Import_Line_Fix

backend/src/utils/common.ts
- fix for maxFeePerGas for Skandha fee return type
-
=> fix: maxFeePerGas field

backend/src/server.ts
- Changes on import statement
-
=> CronJob Updates
